### ISSUE TITLE
Shader doesn't work in VLC

### ISSUE THREAD

**Issue by RomSand** [bauermaximilian/LG-360-VR-for-PC#1]
Hi, thanks for greate project. Activator works, but to activate proximity sensor should be covered. regarding the shader can't get it working , made all the settings but but it doesn't influence on the image. do you know how it can be debuged ? 
Thanks

**Comment by bauermaximilian** [comment]
Heya RomSand! 

First of all, thanks for the feedback - I appreciate it! I'm a bit surprised that you have to cover your proximity sensor though - the activator sends a command to the glasses that deactivates the proximity sensor, and it works on my model without covering the sensor then. Maybe you have a newer firmware version on your glasses or something - but anyways, it's something other users can try if the activator doesn't work on the first try.

Developing the VLC shaders was tricky - because, unfortunately, I didn't find any documentation on how to write shaders for VLC (besides some forum posts and stackoverflow) or how to debug them - so that was more of a trial and error thing. I just tested it again with a fresh install of VLC player 3.0.11 on Windows 10 and it worked - I'm sorry, but I can just give you general advice on eliminating possible errors during setting it up, maybe this helps you out:

First make sure you take the shader from the _most recent_ release [here](https://github.com/bauermaximilian/LG-360-VR-for-PC/releases/) - files from there are guranteed to work and are in the correct encoding (UTF-8 **without** BOM). Try extracting the shader to your desktop first and disable all plugins or filters in your VLC to rule that out. Double-check your settings in VLC so they look (besides your desktop path) _exactly_ like in the following screenshots:

![grafik](https://user-images.githubusercontent.com/21185621/90817175-b486fb80-e32d-11ea-8540-6cf3315488bb.png)
![grafik](https://user-images.githubusercontent.com/21185621/90817131-a507b280-e32d-11ea-8822-ba19a910ae6e.png)

Save the settings, restart the VLC player, and the output should look like this:

![grafik](https://user-images.githubusercontent.com/21185621/90826500-d3d85580-e33a-11ea-8e33-08d57b41f5cd.png)

**Comment by RomSand** [comment]
I think it doen't work with integrated video card trien on gforce GPU and it worked right away.
