### ISSUE TITLE
PCI card recomendation

### ISSUE THREAD

**Issue by beckmx** [bauermaximilian/LG-360-VR-for-PC#4]
Hello there, I noticed in the instructions that you mention you tried with a pci card, may I know which one. I tried with a simple usbc to usbA connector and it does detect it and it does turn it "on" (shadow black) but it doesnt get recognized as second monitor, I guess because of the USBc not fully getting interpreted.

I am excited to get it working, greetings!

**Comment by bauermaximilian** [comment]
Hello there! 
I suppose these "simple" USB-A to USB-C connectors won't work because USB-A doesn't provide the DisplayPort (DP) signal, which has to come from your GPU. The PCI card I mentioned basically has a DP input I had to connect to my graphics card, which then was "forwarded" through the USB-C output to the VR glasses. 
I was successful with the [Sunix UPD2018](https://www.sunix.com/en/product_detail.php?pid=1909) - I got it from Amazon for about 80€. I remember looking for cheaper solutions back then and stumbling over some mentions of adapters with a USB-A and DP input and a USB-C output, but I didn't find them anywhere to order within Europe, so I settled with this card instead.
I hope that helps... good luck with getting it to work!
Best regards,
Max
